name: CI

on: [push]

jobs:
  test:
    name: Test on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Pull submodules
      run: |
        git submodule init
        git submodule update --remote
    - run: apt install lcov
      if: contains(${{ matrix.os }}, "ubuntu")
    - run: brew install lcov
      if: contains(${{ matrix.os }}, "macOS")
    - run: cmake -DCMAKE_BUILD_TYPE=Coverage -H. -Bbuild
    - run: cmake --build build -- -j2
    - run: cmake --build build --target gtest_coverage
      
      
    - uses: codecov/codecov-action@v1.0.2
      if: success()
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
      
    - uses: actions/upload-artifact@master
      if: success()
      with:
        name: cmd-${{ matrix.os }}
        path: build/cmd
